name: Build dev

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: Build and upload artifact
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: subosito/flutter-action@v2

      - name: Build
        run: dotnet build -o outputs\

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build ${{ github.run_number }}
          path: .\outputs\

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: Docs ${{ github.run_number }}
          path: .\outputs\

  release:
    name: release
    needs: [build]
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build
        run: dotnet build -o outputs/

      - name: Make archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: Release.zip

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: Build
          files: Release.zip
